### getMethod for All users

GET http://localhost:3000/questions/getAllQuestions


### post method to Add a User

GET http://localhost:3000/options/getAllOptions
Content-Type: application/json

{
    "userID": 4,
    "name": "New User"
}



###  post method to add an order

POST http://localhost:3000/options/getOptionsByQuestionID
Content-Type: application/json

{
    "questionID": 1
}


###  get method to getAll orders
GET http://localhost:3000/questions/getNextSourceQuestion/1
Content-Type: application/json

{}

### post method to get all users
POST http://localhost:3000/users/getAllUsers
Content-Type: application/json

{}



### post method to get all orders

POST http://localhost:3000/orders/getAllOrders
Content-Type: application/json

{}


###  API to get processed data (first answer)

POST http://localhost:3000/users/userOrderProcessedData
Content-Type: application/json

{}


### API to to update UserOrder Count ( 2nd question answer)

POST http://localhost:3000/users/updateUserOrders
Content-Type: application/json

{}